### ISSUE TITLE
Remote session features

### ISSUE THREAD

**Issue by stephenchernishoff** [mspdna/mspdna-feature-requests#1]
I wanted to know if there was a way to forward key combos while remoted in. For example Windows + R. Locking the windows keys for the desktop side when in the remote session would also be ideal, as clicking windows brings up my own start menu on my side.

Also when there are 2 screens you connect, they seem to show both at the same time. Not really a problem for me, just wasn't sure if it was intentional or if you had that in the works to have the option to show one screen and switch to another.

The option to change the viewing size of the remote session. For now zooming in and out in the browser will be fine but it would be nice to set the size you want by clicking and dragging the corner.

Thank you kindly!

**Comment by darkpixel** [comment]
I took a look at the remote console window code and it appears a recent upgrade broke the automatic resizing.  I have an internal bug filed and that will get fixed in the next release.

**Comment by darkpixel** [comment]
I don't believe I can catch WIN+key combinations in the browser as the Windows shell intercepts them.  From my Linux machine I can use WIN+R to bring up the remote run dialog because my Linux box ignores the WIN key and passes it through.  I can however make some of the common shortcuts into buttons at the top of the console window (similar to the CTRL+ALT+DEL button).

**Comment by darkpixel** [comment]
Internal issue: https://github.com/mspdna/mspdna/issues/37

**Comment by darkpixel** [comment]
The resize fix has been queued for deployment and should show up on production servers over the next 15 minutes.

**Comment by darkpixel** [comment]
Switching between multiple monitors is not supported at the moment.  You will get one window with both monitors.  There may be a possibility to split them in the future, but it will require a change in the way our agent is installed.

**Comment by stephenchernishoff** [comment]
I know you have a button at the top to send a Ctrl+Alt+Del command, how
about adding a windows button that you can toggle on and off. That may be a
good alternative.

Thank you for the speedy resolve on the resize issue!

Switching wont be an issue for me, as long as resize works. It may even be
more convenient with out the screen swap.

On Fri, Jul 14, 2017 at 6:00 PM, Aaron C. de Bruyn <notifications@github.com
